/**
 * THE FAILURE CATALOGUE — SECTION 43.2, SIX FAMILIES OF `FAIL-AI-*` MODES,
 * EACH FAMILY CARRYING THREE ATTRIBUTE TABLES OVER THE SAME ROWS.
 *
 * Every cell below is a verbatim transcription of the source cell at the line
 * the record itself names, and `tests/unit/ai-failures.test.ts` fetches each
 * cell back THROUGH that locator, so a wrong line and a wrong cell fail the
 * same assertion. Nothing here is paraphrased and nothing is summarised.
 *
 * ── WHAT THE THREE TABLES PER FAMILY CARRY ─────────────────────────────────
 * The first names the failure, its detector, its operational severity and the
 * exact strings each surface shows. The second carries the gate, the retry
 * limit, the breaker, the alternate model and the partial-output rule. The
 * third carries the fallback ladder, the terminal safe state, recovery and
 * reconciliation. Same rows, same order, in all three — asserted rather than
 * assumed, because a row present in one table and absent from another would
 * leave attributes unstated and `AC-43-101` (L89973) forbids exactly that.
 *
 * ── HOW A ROW RESOLVES A SPINE ATTRIBUTE, AND WHERE THE JUDGEMENT IS ───────
 * `AC-43-101` requires each row to resolve every spine attribute as inherited,
 * deviated or owed. The source's tables answer only some of the spine's items
 * by column, so the binding between the two is stated here, once per item,
 * with the reason — and it is a BUILD JUDGEMENT, not a source fact. It is
 * written down so a reviewer can disagree with one binding rather than having
 * to re-derive all of them.
 *
 * Two kinds of binding, and the distinction is what stops every row from
 * resolving the same way:
 *
 *   - `selects` — the spine fixes the rule and the row picks from inside it.
 *     Item 1's default already enumerates the detector sources; a row naming
 *     one of them has not displaced anything. The source reads its own
 *     catalogue this way at L89915, where a row with a filled Detection cell
 *     is described as inheriting: "a detector notices rather than a person".
 *   - `displaces` — the row states its own answer where the spine fixed a
 *     different one, or fixed none. Item 3 is the clearest: the spine fixes no
 *     string, so every row's message is a deviation, which is again how the
 *     source reads it at L89915.
 *
 * Above both: a cell pointing at the open register resolves `owed`, whatever
 * its binding. That is the third fate, and it is detected on the tables' own
 * idiom — the bare token `Register`, or one of the register's identifiers.
 *
 * ── ONE COLUMN BINDS TO NO ITEM ON ITS OWN, AND SAYING SO IS THE POINT ─────
 * The `First fallback` column names which rung of the ladder a row enters
 * first. Spine items 8 and 9 say what those rungs ARE, and both say "Always" —
 * item 8's deterministic layer "is never unavailable", item 9's escalation is
 * "always the authored escalation path". So the column selects among rungs the
 * spine already fixed rather than displacing either, and both items bind to it
 * as `selects`. It is written here rather than left implicit because the
 * alternative reading — that a filled `First fallback` cell deviates items 8
 * and 9 on all sixty rows — is defensible and produces a different catalogue.
 */

import {
  SPINE_ITEM_NUMBERS,
  type SpineItemNumber,
} from './spine'
import { severityAssignment, type SeverityAssignment } from './severity'

/** The registry identifiers, in the register's own order. */
const REGISTER_IDS: readonly string[] = [
  'DEC-AIRETRY-001',
  'DEC-AITIMEOUT-001',
  'DEC-AICB-001',
  'DEC-AIFAILOVER-001',
  'DEC-AIQUEUE-001',
  'DEC-AISTALE-001',
  'DEC-AICONF-001',
  'DEC-AIQUAR-001',
  'DEC-AIREPLAY-001',
  'DEC-AITOKEN-001',
]

export type CatalogueCellKey =
  | 'failureMode'
  | 'detection'
  | 'operationalSeverity'
  | 'frontlineMessage'
  | 'tenantWebMessage'
  | 'validationGate'
  | 'retryLimit'
  | 'circuitBreaker'
  | 'alternateModel'
  | 'partialOutput'
  | 'firstFallback'
  | 'fallbackOfFallback'
  | 'terminalSafeState'
  | 'recovery'
  | 'reconciliation'

export type FailureFamilyKey =
  | 'provider-and-model'
  | 'orchestration-and-agent'
  | 'retrieval-memory-and-content'
  | 'governance-evaluation-and-gate'
  | 'connectivity-device-and-sync'
  | 'recovery-reconciliation-and-stale-state'

export interface FailureFamily {
  readonly key: FailureFamilyKey
  /** The section heading, verbatim and without its markdown hashes. */
  readonly title: string
  readonly headingLocator: number
  /** The three attribute tables' header lines, in the order the source runs them. */
  readonly attributeTableHeaders: readonly number[]
}

export interface CatalogueRow {
  readonly id: string
  readonly family: FailureFamilyKey
  /** This row's line in each of its family's three attribute tables. */
  readonly attributeLocators: readonly number[]
  readonly cells: Readonly<Record<CatalogueCellKey, string>>
  readonly severity: SeverityAssignment
  /**
   * Every `DEC-*` identifier this row's own cells name. NOT only the ten of
   * the open register: the cells also reach `DEC-AGENTLC-001`,
   * `DEC-NOSHIFT-001`, `DEC-SUSP-001`, `DEC-STORE-001`, `DEC-WIPE-001` and two
   * — `DEC-AIEMBED-001` and `DEC-AIFALLBACK-001` — that this build's decision
   * canon does not hold at all. Keeping them here rather than filtering to the
   * register is what lets a later task see that gap instead of inheriting it.
   */
  readonly citedDecisions: readonly string[]
}

/** How a spine item's answer is carried, if it is carried by a column at all. */
export type SpineBindingKind = 'selects' | 'displaces'

export interface SpineBinding {
  readonly item: SpineItemNumber
  readonly columns: readonly CatalogueCellKey[]
  /** `null` exactly where `columns` is empty. */
  readonly kind: SpineBindingKind | null
  readonly reason: string
}

export const SPINE_BINDINGS = [
  {
    item: 1,
    columns: ['detection'],
    kind: 'selects',
    reason:
      'The default already enumerates the detector sources; a row names which of them fires.',
  },
  {
    item: 2,
    columns: ['operationalSeverity'],
    kind: 'selects',
    reason: 'The default fixes the bands; a row names which band, or the condition between two.',
  },
  {
    item: 3,
    columns: ['frontlineMessage', 'tenantWebMessage'],
    kind: 'displaces',
    reason: 'The default fixes no string, so every row writes its own for each surface.',
  },
  {
    item: 4,
    columns: ['validationGate'],
    kind: 'selects',
    reason:
      'The default fixes the rule that no output reaches a surface ungated; a row names which assertion applies.',
  },
  {
    item: 5,
    columns: ['retryLimit'],
    kind: 'displaces',
    reason: 'The default is `Not specified in the Statement of Work`, so a stated cell fixes it.',
  },
  {
    item: 6,
    columns: ['circuitBreaker'],
    kind: 'displaces',
    reason: 'The default is `Not specified in the Statement of Work`, so a stated cell fixes it.',
  },
  {
    item: 7,
    columns: ['alternateModel'],
    kind: 'displaces',
    reason: 'The default establishes that a fallback role exists and states no policy.',
  },
  {
    item: 8,
    columns: ['firstFallback'],
    kind: 'selects',
    reason:
      'The default says the deterministic layer is always the same and never unavailable; the column names whether it is entered first.',
  },
  {
    item: 9,
    columns: ['firstFallback'],
    kind: 'selects',
    reason:
      'The default says the escalation path is always the authored one; the column names whether it is entered first.',
  },
  {
    item: 10,
    columns: ['fallbackOfFallback'],
    kind: 'displaces',
    reason: 'The default fixes deterministic no-artificial-intelligence mode; a cell naming another rung displaces it.',
  },
  {
    item: 11,
    columns: ['terminalSafeState'],
    kind: 'displaces',
    reason: 'The default fixes continue-where-safe and hold otherwise; a cell states this row’s ending.',
  },
  {
    item: 12,
    columns: [],
    kind: null,
    reason: 'No column. Roles are fixed once for the platform side and once for the tenant side.',
  },
  {
    item: 13,
    columns: [],
    kind: null,
    reason:
      'No column. The default says so itself: defined once per surface in section 43.3 and inherited by every row.',
  },
  {
    item: 14,
    columns: ['partialOutput'],
    kind: 'displaces',
    reason:
      'The default fixes quarantine-never-discard; several cells state something else, including one that discards.',
  },
  {
    item: 15,
    columns: [],
    kind: null,
    reason: 'No column. Data preservation is invariant across the catalogue.',
  },
  {
    item: 16,
    columns: ['recovery'],
    kind: 'displaces',
    reason: 'The default fixes automatic-or-approval-cycled; a cell states this row’s route.',
  },
  {
    item: 17,
    columns: ['reconciliation'],
    kind: 'displaces',
    reason: 'The default fixes recompute-with-an-as-of-stamp; a cell states this row’s obligation.',
  },
  {
    item: 18,
    columns: [],
    kind: null,
    reason: 'No column. Rollback runs the same approval cycle that applied the change.',
  },
  { item: 19, columns: [], kind: null, reason: 'No column. Audit commits with the action or the action does not happen.' },
  { item: 20, columns: [], kind: null, reason: 'No column. Every failure has a metric, a threshold and an owner.' },
  {
    item: 21,
    columns: [],
    kind: null,
    reason: 'No column. Every failure carries at least a fault-injection test in the `TEST-43-001` suite.',
  },
] as const satisfies readonly SpineBinding[]

export const FAILURE_FAMILIES = [
  { key: "provider-and-model", title: "43.2.1 Provider and model layer — `FAIL-AI-01` to `FAIL-AI-12`", headingLocator: 90100, attributeTableHeaders: [90122, 90139, 90156] },
  { key: "orchestration-and-agent", title: "43.2.2 Orchestration and agent layer — `FAIL-AI-13` to `FAIL-AI-24`", headingLocator: 90227, attributeTableHeaders: [90249, 90266, 90283] },
  { key: "retrieval-memory-and-content", title: "43.2.3 Retrieval, memory, and content layer — `FAIL-AI-25` to `FAIL-AI-36`", headingLocator: 90351, attributeTableHeaders: [90372, 90389, 90406] },
  { key: "governance-evaluation-and-gate", title: "43.2.4 Governance, evaluation, and gate layer — `FAIL-AI-37` to `FAIL-AI-46`", headingLocator: 90487, attributeTableHeaders: [90507, 90522, 90537] },
  { key: "connectivity-device-and-sync", title: "43.2.5 Connectivity, device, and sync layer — `FAIL-AI-47` to `FAIL-AI-54`", headingLocator: 90600, attributeTableHeaders: [90621, 90634, 90647] },
  { key: "recovery-reconciliation-and-stale-state", title: "43.2.6 Recovery, reconciliation, and stale-state layer — `FAIL-AI-55` to `FAIL-AI-60`", headingLocator: 90706, attributeTableHeaders: [90727, 90738, 90749] },
] as const satisfies readonly FailureFamily[]

export const FAILURE_CATALOGUE = [
  {
    id: "FAIL-AI-01",
    family: "provider-and-model",
    attributeLocators: [90124, 90141, 90158],
    cells: {
      failureMode: "Cloud provider outage, total",
      detection: "Health probe failure plus error-rate threshold",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable. Approved instructions and safety checks are running on this device.\"",
      tenantWebMessage: "\"Agent capabilities are unavailable. Platform operations has been notified. Deterministic checks are unaffected.\"",
      validationGate: "Not reached — no output produced",
      retryLimit: "Register `DEC-AIRETRY-001`",
      circuitBreaker: "Register `DEC-AICB-001`",
      alternateModel: "Fallback router role under `DEC-AIFAILOVER-001`, evaluation gate re-asserted",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Approved cached guidance, `AIMODE-06`",
      fallbackOfFallback: "Deterministic only, `AIMODE-07`",
      terminalSafeState: "Deterministic execution continues; hold only if a deviation independently requires one",
      recovery: "Half-open probe succeeds",
      reconciliation: "Pending artificial-intelligence fields recompute with as-of stamps",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: ["DEC-AICB-001", "DEC-AIFAILOVER-001", "DEC-AIRETRY-001"],
  },
  {
    id: "FAIL-AI-02",
    family: "provider-and-model",
    attributeLocators: [90125, 90142, 90159],
    cells: {
      failureMode: "Provider partial or regional degradation",
      detection: "Latency threshold breach on a subset of calls",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching slow.\"",
      tenantWebMessage: "\"Agent capabilities are degraded. Some outputs may be delayed.\"",
      validationGate: "Standard evaluation gate",
      retryLimit: "Register",
      circuitBreaker: "Register, per role",
      alternateModel: "Fallback router role under `DEC-AIFAILOVER-001`",
      partialOutput: "Quarantined if the call is abandoned mid-stream",
      firstFallback: "Degraded mode with longer deadlines",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Latency returns below threshold for a sustained window",
      reconciliation: "Delayed outputs delivered with their true produced-at time",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-AIFAILOVER-001"],
  },
  {
    id: "FAIL-AI-03",
    family: "provider-and-model",
    attributeLocators: [90126, 90143, 90160],
    cells: {
      failureMode: "Rate limit or quota exhaustion",
      detection: "Provider rate-limit response class",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Agent capacity limit reached for this period. Platform operations has been notified.\"",
      validationGate: "Not reached",
      retryLimit: "Register, with backoff mandatory",
      circuitBreaker: "Register",
      alternateModel: "Lightweight router role where the task permits",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Lightweight role, then cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Quota window resets or ceiling raised through the approval cycle",
      reconciliation: "Suppressed activations recorded so the activity panel counts are honest",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-04",
    family: "provider-and-model",
    attributeLocators: [90127, 90144, 90161],
    cells: {
      failureMode: "Authentication or key-rotation failure",
      detection: "Authentication error class on every call to a role",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Agent capabilities are unavailable. Platform operations has been notified.\"",
      validationGate: "Not reached",
      retryLimit: "No retry — retrying an authentication failure is never productive",
      circuitBreaker: "Immediate open",
      alternateModel: "Fallback role if separately credentialed",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Credential rotation completed as an approval-cycled change",
      reconciliation: "Incident report to affected tenants",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-05",
    family: "provider-and-model",
    attributeLocators: [90128, 90145, 90162],
    cells: {
      failureMode: "Model endpoint deprecated or removed",
      detection: "Model-not-found error class; release-note monitoring",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Agent capabilities are unavailable pending a platform change.\"",
      validationGate: "Not reached",
      retryLimit: "No retry",
      circuitBreaker: "Immediate open",
      alternateModel: "Fallback role, evaluation gate re-asserted for the substituted model",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Fallback model with the evaluation gate re-asserted",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Model migration approved and evaluated",
      reconciliation: "Outputs produced by the retired model remain attributed to it",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-06",
    family: "provider-and-model",
    attributeLocators: [90129, 90146, 90163],
    cells: {
      failureMode: "Model latency beyond the loop timeout",
      detection: "Loop timeout under `DEC-AITIMEOUT-001`",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching slow.\"",
      tenantWebMessage: "\"Agent outputs are delayed.\"",
      validationGate: "Standard evaluation gate",
      retryLimit: "Register",
      circuitBreaker: "Register",
      alternateModel: "Lightweight router role",
      partialOutput: "Quarantined with its trace",
      firstFallback: "Extend to the deadline, then abandon",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Latency recovery",
      reconciliation: "Abandoned runs recorded as failed activations, not as silence",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-AITIMEOUT-001"],
  },
  {
    id: "FAIL-AI-07",
    family: "provider-and-model",
    attributeLocators: [90130, 90147, 90164],
    cells: {
      failureMode: "Malformed or unparseable output",
      detection: "Schema validation failure at the atom boundary",
      operationalSeverity: "Major",
      frontlineMessage: "No message; the card simply does not appear and the mode chip is unchanged",
      tenantWebMessage: "\"One agent output was rejected by validation and was not published.\"",
      validationGate: "Schema validation, hard",
      retryLimit: "Register, bounded — repeated malformation indicates a model problem, not a transient one",
      circuitBreaker: "Register",
      alternateModel: "Fallback role after the second consecutive schema failure",
      partialOutput: "Quarantined; never repaired heuristically",
      firstFallback: "Single bounded retry",
      fallbackOfFallback: "Suppress and fall back to cached guidance",
      terminalSafeState: "Deterministic execution",
      recovery: "Model or prompt fix through the approval cycle",
      reconciliation: "Quarantined outputs reviewed; none published",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-08",
    family: "provider-and-model",
    attributeLocators: [90131, 90148, 90165],
    cells: {
      failureMode: "Empty output",
      detection: "Zero-length or content-free response",
      operationalSeverity: "Minor",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent output was empty and was not published.\"",
      validationGate: "Content-presence validation",
      retryLimit: "Register",
      circuitBreaker: "Register",
      alternateModel: "Fallback role",
      partialOutput: "Not applicable — there is no content to quarantine",
      firstFallback: "Single bounded retry",
      fallbackOfFallback: "Suppress and fall back to cached guidance",
      terminalSafeState: "Deterministic execution",
      recovery: "Model fix",
      reconciliation: "Empty-output rate monitored as a quality signal",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-09",
    family: "provider-and-model",
    attributeLocators: [90132, 90149, 90166],
    cells: {
      failureMode: "Output in the wrong locale",
      detection: "Locale assertion against the worker's profile language",
      operationalSeverity: "Major",
      frontlineMessage: "No message; the card is suppressed and the packaged asset renders instead",
      tenantWebMessage: "\"One agent output failed the language check and was not shown.\"",
      validationGate: "Locale assertion, hard — nothing is machine-translated at runtime",
      retryLimit: "No retry into the same locale path",
      circuitBreaker: "Register",
      alternateModel: "Not applicable — an alternate model does not fix a locale defect",
      partialOutput: "Quarantined for content review",
      firstFallback: "Suppress and render the packaged asset in the correct locale",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Corpus or model fix",
      reconciliation: "Locale-failure rate reported to the tenant's Quality Manager as a content signal",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-10",
    family: "provider-and-model",
    attributeLocators: [90133, 90150, 90167],
    cells: {
      failureMode: "Embedding model unavailable",
      detection: "Embedding role health probe",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Coaching retrieval is unavailable. Authored instructions are unaffected.\"",
      validationGate: "Not reached — retrieval cannot run",
      retryLimit: "Register",
      circuitBreaker: "Register",
      alternateModel: "Alternate embedding model only with a full re-index; see `DEC-AIEMBED-001`",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Curated default asset from the package",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Embedding role restored",
      reconciliation: "Retrieval quality re-evaluated per §8.5.2 retrieval evaluations",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: ["DEC-AIEMBED-001"],
  },
  {
    id: "FAIL-AI-11",
    family: "provider-and-model",
    attributeLocators: [90134, 90151, 90168],
    cells: {
      failureMode: "Semantic cache stale or poisoned",
      detection: "Cache-entry validation against corpus version",
      operationalSeverity: "Major",
      frontlineMessage: "No message; cache bypassed",
      tenantWebMessage: "\"Coaching retrieval is bypassing its cache while it rebuilds.\"",
      validationGate: "Cache-entry version assertion",
      retryLimit: "No retry — the cache is bypassed, not retried",
      circuitBreaker: "Not applicable — a cache bypass is not a breaker condition",
      alternateModel: "Not applicable — the live path is the alternate",
      partialOutput: "Poisoned entries quarantined for inspection, then evicted",
      firstFallback: "Live retrieval with the cache bypassed",
      fallbackOfFallback: "Curated default asset",
      terminalSafeState: "Deterministic execution",
      recovery: "Cache rebuilt against the current corpus version",
      reconciliation: "Cache hit-rate and staleness reported",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-12",
    family: "provider-and-model",
    attributeLocators: [90135, 90152, 90169],
    cells: {
      failureMode: "Per-tenant token ceiling breached",
      detection: "Token telemetry against the ceiling of `DEC-AITOKEN-001`",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"This workspace has reached its agent capacity for the period. Your platform contact has been notified.\"",
      validationGate: "Not reached",
      retryLimit: "No retry — retrying a ceiling breach is futile",
      circuitBreaker: "Immediate open for that tenant",
      alternateModel: "Not applicable — the ceiling is commercial, not technical",
      partialOutput: "Not applicable — no output was produced",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Ceiling change through the approval cycle, or the period resets",
      reconciliation: "Usage ledger reconciled; the breach is a commercial event, not merely technical",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-AITOKEN-001"],
  },
  {
    id: "FAIL-AI-13",
    family: "orchestration-and-agent",
    attributeLocators: [90251, 90268, 90285],
    cells: {
      failureMode: "Plan-step limit exceeded",
      detection: "Step counter against max plan steps",
      operationalSeverity: "Major",
      frontlineMessage: "No message; no card appears",
      tenantWebMessage: "\"One agent run stopped at its planning limit and produced no output.\"",
      validationGate: "Not reached",
      retryLimit: "No retry — a re-run repeats the plan",
      circuitBreaker: "Not applicable — this is a bound, not a dependency failure",
      alternateModel: "Not applicable — the model is healthy",
      partialOutput: "Quarantined with the full trace",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Plan-bound review and scenario coverage",
      reconciliation: "Activity counters record a failed activation",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-14",
    family: "orchestration-and-agent",
    attributeLocators: [90252, 90269, 90286],
    cells: {
      failureMode: "Replan limit exceeded",
      detection: "Replan counter against max replans",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent run needed a person and has been escalated.\"",
      validationGate: "Not reached",
      retryLimit: "No retry — the bound exists precisely to stop retrying",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined; the escalation carries the partial reasoning summary, never the raw trace",
      firstFallback: "Human escalation, which is the control's stated intent",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution with a human decision pending",
      recovery: "Human decides; the agent does not resume the abandoned plan",
      reconciliation: "The escalation and its outcome are recorded against the run",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-15",
    family: "orchestration-and-agent",
    attributeLocators: [90253, 90270, 90287],
    cells: {
      failureMode: "Runaway or non-terminating loop",
      detection: "Loop timeout plus the runaway kill switch",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Agent activity was stopped by a safety control. Platform operations has been notified.\"",
      validationGate: "Not reached",
      retryLimit: "No retry",
      circuitBreaker: "Kill switch, which is a breaker by another name",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined with the full trace for engineering",
      firstFallback: "Immediate termination at a stage boundary",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Engineering fix through the approval cycle",
      reconciliation: "The killed run is recorded as a platform incident",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-16",
    family: "orchestration-and-agent",
    attributeLocators: [90254, 90271, 90288],
    cells: {
      failureMode: "Tool-call budget exhausted",
      detection: "Budget counter",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent run reached its tool budget and produced no output.\"",
      validationGate: "Not reached",
      retryLimit: "No retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Budget review",
      reconciliation: "Counters record a failed activation",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-17",
    family: "orchestration-and-agent",
    attributeLocators: [90255, 90272, 90289],
    cells: {
      failureMode: "Atom invocation failure",
      detection: "Atom error class against declared postconditions",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent step failed and the run produced no output.\"",
      validationGate: "Atom postcondition assertion",
      retryLimit: "Register, bounded per atom",
      circuitBreaker: "Register, per atom",
      alternateModel: "Not applicable — atoms have no alternates",
      partialOutput: "Quarantined",
      firstFallback: "Retry within budget, then cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Atom fix through the approval cycle",
      reconciliation: "Atom failure rate monitored per atom",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-18",
    family: "orchestration-and-agent",
    attributeLocators: [90256, 90273, 90290],
    cells: {
      failureMode: "Atom disabled mid-run",
      detection: "Enablement state changed during an active run",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"A platform capability changed during an agent run; the run produced no output.\"",
      validationGate: "Enablement assertion at invocation",
      retryLimit: "No retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Enablement restored through the approval cycle",
      reconciliation: "Runs affected by the change are listed in the change record",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-19",
    family: "orchestration-and-agent",
    attributeLocators: [90257, 90274, 90291],
    cells: {
      failureMode: "Atom schema mismatch after a version change",
      detection: "Input or output schema validation",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Agent capabilities are unavailable pending a platform change.\"",
      validationGate: "Schema validation, hard",
      retryLimit: "No retry",
      circuitBreaker: "Immediate open for that atom",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Schema migration approved and evaluated",
      reconciliation: "Every agent depending on the atom is re-evaluated before re-enablement",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-20",
    family: "orchestration-and-agent",
    attributeLocators: [90258, 90275, 90292],
    cells: {
      failureMode: "Agent record disabled mid-run",
      detection: "Agent status changed during an active run",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"An agent was disabled during a run; the run produced no output.\"",
      validationGate: "Agent status assertion",
      retryLimit: "No retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Agent re-enabled through the approval cycle",
      reconciliation: "In-flight run disposition recorded; see `DEC-AGENTLC-001`",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-AGENTLC-001"],
  },
  {
    id: "FAIL-AI-21",
    family: "orchestration-and-agent",
    attributeLocators: [90259, 90276, 90293],
    cells: {
      failureMode: "Composed agent fails evaluation after deployment",
      detection: "Drift canary evaluation failure",
      operationalSeverity: "Critical",
      frontlineMessage: "No message; the composed agent simply stops acting",
      tenantWebMessage: "\"A composed agent has been disabled because its evaluation scenarios are failing.\"",
      validationGate: "Evaluation gate, hard — an enabled capability whose evaluations start failing is flagged immediately",
      retryLimit: "Not applicable",
      circuitBreaker: "Immediate disablement",
      alternateModel: "Not applicable",
      partialOutput: "All outputs since the last passing evaluation run are reviewed, none retracted silently",
      firstFallback: "Immediate disablement, which the evaluation gate compels",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Composed agent resubmitted through tenant approval, platform review, and evaluation",
      reconciliation: "Outputs produced since the last passing run are labelled for the tenant's Quality Manager to review",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-22",
    family: "orchestration-and-agent",
    attributeLocators: [90260, 90277, 90294],
    cells: {
      failureMode: "Output references a nonexistent asset",
      detection: "Asset resolution failure at render time",
      operationalSeverity: "Major",
      frontlineMessage: "No message; packaged asset renders instead",
      tenantWebMessage: "\"One coaching output referenced missing content and was not shown.\"",
      validationGate: "Asset resolution assertion",
      retryLimit: "Single bounded retry after re-index",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Curated default asset",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Corpus re-index",
      reconciliation: "Broken references reported to the tenant as a content signal",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-23",
    family: "orchestration-and-agent",
    attributeLocators: [90261, 90278, 90295],
    cells: {
      failureMode: "Per-tenant concurrency limit reached",
      detection: "Concurrency counter",
      operationalSeverity: "Minor",
      frontlineMessage: "No message",
      tenantWebMessage: "\"Agent requests are queuing behind current activity.\"",
      validationGate: "Not reached",
      retryLimit: "Queued rather than retried",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable — nothing was produced",
      firstFallback: "Queue and serve in order",
      fallbackOfFallback: "Cached guidance if the queue wait exceeds usefulness",
      terminalSafeState: "Deterministic execution",
      recovery: "Concurrency headroom restored",
      reconciliation: "Queue latency reported",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-24",
    family: "orchestration-and-agent",
    attributeLocators: [90262, 90279, 90296],
    cells: {
      failureMode: "Action proposal beyond pre-authorised policy with no human available",
      detection: "Gate raised with no holder of the target role on shift",
      operationalSeverity: "Critical",
      frontlineMessage: "No message; the deterministic path is unaffected",
      tenantWebMessage: "\"A decision is waiting and no one holding the required role is on shift. It has been delivered to the Quality Manager role as a fallback.\"",
      validationGate: "Human gate, hard",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The proposal is held at the gate, never auto-applied",
      firstFallback: "Fallback delivery to the tenant's Quality Manager role irrespective of shift, marked as a fallback delivery",
      fallbackOfFallback: "Gate remains open and human-decidable indefinitely rather than timing out into action",
      terminalSafeState: "No action taken without a human decision",
      recovery: "A human decides",
      reconciliation: "The fallback delivery is visibly marked in the record",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-25",
    family: "retrieval-memory-and-content",
    attributeLocators: [90374, 90391, 90408],
    cells: {
      failureMode: "Corpus index unavailable",
      detection: "Index health probe",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Coaching retrieval is unavailable. Approved instructions are unaffected.\"",
      validationGate: "Not reached",
      retryLimit: "Register",
      circuitBreaker: "Register",
      alternateModel: "Alternate embedding model only with a full re-index; see `DEC-AIEMBED-001`",
      partialOutput: "Not applicable — nothing was produced",
      firstFallback: "Curated default asset from the package",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Index restored",
      reconciliation: "Retrieval evaluations re-run before coaching resumes",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: ["DEC-AIEMBED-001"],
  },
  {
    id: "FAIL-AI-26",
    family: "retrieval-memory-and-content",
    attributeLocators: [90375, 90392, 90409],
    cells: {
      failureMode: "Re-index incomplete after a content update",
      detection: "Index version behind corpus version",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"Recently added coaching content is not yet searchable.\"",
      validationGate: "Index-version assertion",
      retryLimit: "Retry after re-index completion",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Retrieval over the previous index version, labelled honestly",
      fallbackOfFallback: "Curated default asset",
      terminalSafeState: "Deterministic execution",
      recovery: "Re-index completes",
      reconciliation: "Newly added assets become searchable; the tenant is told when",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-27",
    family: "retrieval-memory-and-content",
    attributeLocators: [90376, 90393, 90410],
    cells: {
      failureMode: "No candidate above the relevance floor",
      detection: "Score below `DEC-AICONF-001`",
      operationalSeverity: "Minor",
      frontlineMessage: "No message; the packaged default renders",
      tenantWebMessage: "\"No suitable coaching asset was found for this situation.\"",
      validationGate: "Relevance floor `DEC-AICONF-001`",
      retryLimit: "No retry — a re-query returns the same corpus",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Curated default asset",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Corpus improvement by the tenant's quality team",
      reconciliation: "Low-relevance rate reported so the Quality Manager can retire or add assets",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: ["DEC-AICONF-001"],
  },
  {
    id: "FAIL-AI-28",
    family: "retrieval-memory-and-content",
    attributeLocators: [90377, 90394, 90411],
    cells: {
      failureMode: "Candidate only in the wrong locale",
      detection: "Locale assertion",
      operationalSeverity: "Major",
      frontlineMessage: "No message; the packaged default renders in the correct locale",
      tenantWebMessage: "\"No coaching asset exists in this worker's language for this screen.\"",
      validationGate: "Locale assertion, hard",
      retryLimit: "No retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable — no model substitution creates missing content",
      partialOutput: "Not applicable",
      firstFallback: "Curated default asset in the correct locale",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Tenant authors the missing language variant",
      reconciliation: "Locale-gap report to the tenant",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-29",
    family: "retrieval-memory-and-content",
    attributeLocators: [90378, 90395, 90412],
    cells: {
      failureMode: "Metadata filter failure",
      detection: "Filter assertion before ranking",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Coaching retrieval has been suspended by a safety control.\"",
      validationGate: "Filter assertion, hard",
      retryLimit: "No retry — a filter failure is never retried into the same path",
      circuitBreaker: "Immediate open for retrieval",
      alternateModel: "Not applicable",
      partialOutput: "Any ranked set produced without the filter is discarded before use and quarantined for inspection",
      firstFallback: "Retrieval suspended entirely",
      fallbackOfFallback: "Curated default asset then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Engineering fix, evaluation re-run",
      reconciliation: "Every retrieval during the window is reviewed for leakage",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-30",
    family: "retrieval-memory-and-content",
    attributeLocators: [90379, 90396, 90413],
    cells: {
      failureMode: "Curated default missing for the locale",
      detection: "Package-readiness check",
      operationalSeverity: "Major",
      frontlineMessage: "\"No coaching content is available for this step. Follow the approved instructions above.\"",
      tenantWebMessage: "\"One or more screens have no coaching fallback in an enabled language.\"",
      validationGate: "Package-readiness check",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Authored Work Instructions alone",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Tenant authors the default",
      reconciliation: "Package-readiness report; see `DEC-AIFALLBACK-001`",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-AIFALLBACK-001"],
  },
  {
    id: "FAIL-AI-31",
    family: "retrieval-memory-and-content",
    attributeLocators: [90380, 90397, 90414],
    cells: {
      failureMode: "A memory store unavailable",
      detection: "Store health probe per type",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching slow.\" or \"Live coaching unavailable.\" depending on the store",
      tenantWebMessage: "\"Agent context is degraded. Outputs may be less specific.\"",
      validationGate: "Store health assertion",
      retryLimit: "Register",
      circuitBreaker: "Register, per store",
      alternateModel: "Not applicable — stores have no alternates",
      partialOutput: "Quarantined",
      firstFallback: "Reduced-context reasoning where the store is non-essential",
      fallbackOfFallback: "Curated default asset then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Store restored",
      reconciliation: "Episodic gaps recorded so history is not silently incomplete",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-32",
    family: "retrieval-memory-and-content",
    attributeLocators: [90381, 90398, 90415],
    cells: {
      failureMode: "Working memory lost mid-run",
      detection: "Run-context assertion",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent run lost its context and produced no output.\"",
      validationGate: "Run-context assertion",
      retryLimit: "No retry — the context is gone",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined",
      firstFallback: "Abandon the run",
      fallbackOfFallback: "Curated default asset then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Next trigger starts a fresh run",
      reconciliation: "Failed activation recorded",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-33",
    family: "retrieval-memory-and-content",
    attributeLocators: [90382, 90399, 90416],
    cells: {
      failureMode: "Memory write failure after a successful output",
      detection: "Write acknowledgement missing",
      operationalSeverity: "Minor",
      frontlineMessage: "No message",
      tenantWebMessage: "\"One agent outcome was not recorded for learning.\"",
      validationGate: "Write acknowledgement",
      retryLimit: "Register, bounded",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The output stands; only the learning write failed",
      firstFallback: "Retry the write",
      fallbackOfFallback: "Record the gap explicitly",
      terminalSafeState: "Deterministic execution unaffected",
      recovery: "Store restored",
      reconciliation: "Lane A learning signals reconciled; unrecorded outcomes flagged so learning is not silently biased",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-34",
    family: "retrieval-memory-and-content",
    attributeLocators: [90383, 90400, 90417],
    cells: {
      failureMode: "Profile-memory redaction failure",
      detection: "Redaction assertion before write",
      operationalSeverity: "Critical",
      frontlineMessage: "No message",
      tenantWebMessage: "\"A learning write was blocked by a privacy control.\"",
      validationGate: "Redaction assertion, hard",
      retryLimit: "No retry",
      circuitBreaker: "Immediate open for profile writes",
      alternateModel: "Not applicable",
      partialOutput: "The unredacted candidate is discarded, never stored",
      firstFallback: "Discard the write",
      fallbackOfFallback: "Suspend profile writes",
      terminalSafeState: "Deterministic execution unaffected",
      recovery: "Redaction fix, approval-cycled",
      reconciliation: "Privacy incident recorded; the redaction policy is console-administered",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-35",
    family: "retrieval-memory-and-content",
    attributeLocators: [90384, 90401, 90418],
    cells: {
      failureMode: "Cross-tenant retrieval attempt detected",
      detection: "Tenant-scope assertion on every retrieval",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"Coaching retrieval has been suspended by a safety control. Platform operations has been notified.\"",
      validationGate: "Tenant-scope assertion, hard",
      retryLimit: "No retry",
      circuitBreaker: "Immediate open, platform-wide for that path",
      alternateModel: "Not applicable",
      partialOutput: "Every candidate discarded; the event is a security incident",
      firstFallback: "Suspend retrieval platform-wide for that path",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Engineering fix plus a security review",
      reconciliation: "Full audit of the window; isolation is an enforced invariant with no off switch",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-36",
    family: "retrieval-memory-and-content",
    attributeLocators: [90385, 90402, 90419],
    cells: {
      failureMode: "Instruction-shaped content detected in worker free text or an uploaded asset",
      detection: "Guardrail classification",
      operationalSeverity: "Major",
      frontlineMessage: "No message; the request proceeds with the text treated strictly as data",
      tenantWebMessage: "\"One request contained content that was treated as data rather than instruction.\"",
      validationGate: "Guardrail classification",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The classified content is retained as evidence of the attempt",
      firstFallback: "Proceed with the content treated strictly as data",
      fallbackOfFallback: "Suppress the request",
      terminalSafeState: "Deterministic execution unaffected",
      recovery: "Guardrail tuning",
      reconciliation: "Attempt rate monitored as a security signal",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-37",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90509, 90524, 90539],
    cells: {
      failureMode: "Evaluation failing for an enabled capability",
      detection: "Drift canary suite run on cadence",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching unavailable.\"",
      tenantWebMessage: "\"A capability has been disabled because its evaluation scenarios are failing.\"",
      validationGate: "Evaluation gate, ENFORCED",
      retryLimit: "Not applicable",
      circuitBreaker: "Immediate disablement",
      alternateModel: "Not applicable — an alternate model does not fix a failing scenario",
      partialOutput: "Outputs since the last passing run are labelled for review, never retracted silently",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Scenario fixed and the suite passes",
      reconciliation: "Outputs in the failing window reviewed by the tenant's Quality Manager",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-38",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90510, 90525, 90540],
    cells: {
      failureMode: "Evaluation harness itself unavailable",
      detection: "Harness health probe",
      operationalSeverity: "Critical",
      frontlineMessage: "No immediate change",
      tenantWebMessage: "\"New capability changes are paused while platform checks are unavailable.\"",
      validationGate: "Not reached",
      retryLimit: "Register",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable — no new enablement occurs",
      firstFallback: "Existing enabled capabilities keep running; no new enablement",
      fallbackOfFallback: "Deterministic only if the harness loss cascades",
      terminalSafeState: "Deterministic execution",
      recovery: "Harness restored",
      reconciliation: "The enablement queue is drained in order once checks resume",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-39",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90511, 90526, 90541],
    cells: {
      failureMode: "Gate item times out unacknowledged",
      detection: "Gate timer, ten minutes Severity 1 and thirty minutes otherwise",
      operationalSeverity: "Major",
      frontlineMessage: "No message; deterministic path unaffected",
      tenantWebMessage: "\"A decision has passed its response time and has been escalated.\"",
      validationGate: "Human gate, hard",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The proposal is held, never applied",
      firstFallback: "Escalation per the tenant's routing",
      fallbackOfFallback: "Fallback delivery to the Quality Manager role",
      terminalSafeState: "Gate open and human-decidable; no action taken",
      recovery: "A human decides",
      reconciliation: "Timer breaches recorded as gate-health metrics feeding platform telemetry",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-40",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90512, 90527, 90542],
    cells: {
      failureMode: "Nobody holding the target role on shift",
      detection: "Role resolution returns empty",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"No one holding the required role is on shift. Delivered to the Quality Manager role as a fallback.\"",
      validationGate: "Human gate, hard",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The proposal is held and delivered as a marked fallback",
      firstFallback: "Fallback delivery to the Quality Manager role irrespective of shift, visibly marked",
      fallbackOfFallback: "Gate remains open indefinitely rather than timing out into action",
      terminalSafeState: "No action without a human",
      recovery: "A human decides",
      reconciliation: "Fallback deliveries counted; `DEC-NOSHIFT-001` remains open",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-NOSHIFT-001"],
  },
  {
    id: "FAIL-AI-41",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90513, 90528, 90543],
    cells: {
      failureMode: "Emergency pause, platform-wide",
      detection: "Pause state",
      operationalSeverity: "Critical",
      frontlineMessage: "\"Live coaching paused by the platform.\"",
      tenantWebMessage: "\"Agents paused by the platform. Deterministic checks are unaffected.\"",
      validationGate: "Not reached",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "In-flight runs checkpoint at a stage boundary and park",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution continues untouched",
      recovery: "Resume as a separate audited critical-class act",
      reconciliation: "Parked runs are listed; none resume automatically",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-42",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90514, 90529, 90544],
    cells: {
      failureMode: "Emergency pause, per tenant",
      detection: "Pause state",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching paused by the platform.\"",
      tenantWebMessage: "\"Agents paused by the platform for this workspace.\"",
      validationGate: "Not reached",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "In-flight runs checkpoint and park",
      firstFallback: "Cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Deterministic execution continues untouched",
      recovery: "Resume as a separate audited act",
      reconciliation: "Parked runs listed for that tenant",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-43",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90515, 90530, 90545],
    cells: {
      failureMode: "Tenant suspension intersecting an agent run",
      detection: "Suspension state",
      operationalSeverity: "Critical for compliance suspension, Major otherwise",
      frontlineMessage: "Compliance case, verbatim: \"Operation suspended. Contact your supervisor. Your work has been saved.\"",
      tenantWebMessage: "\"This workspace is suspended. Agent activity has stopped.\"",
      validationGate: "Not reached",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "In-flight runs stop; local data is preserved",
      firstFallback: "For soft suspension, operations continue in full; for hard, the enumerated completion pipeline; for compliance, immediate lock with data preserved",
      fallbackOfFallback: "Deterministic only where operations continue",
      terminalSafeState: "Compliance case: device locked, all local data preserved, fixed message shown",
      recovery: "Suspension lifted per its state machine; the soft-state exit is an explicit operator signal under the adopted working position of `DEC-SUSP-001`",
      reconciliation: "In-flight run disposition recorded per the suspension state",
    },
    severity: { kind: 'conditional', bands: ["Critical", "Major"], cell: "Critical for compliance suspension, Major otherwise" },
    citedDecisions: ["DEC-SUSP-001"],
  },
  {
    id: "FAIL-AI-44",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90516, 90531, 90546],
    cells: {
      failureMode: "Approval chain unavailable for a Lane-B proposal",
      detection: "No approver-capable role reachable",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"A learned-change proposal is waiting for a decision.\"",
      validationGate: "Human decision, hard — Lane B is never auto-approved",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The proposal ages with a thirty-day stale flag and never expires silently",
      firstFallback: "The proposal waits; nothing is applied",
      fallbackOfFallback: "Stale flag at thirty days, still waiting",
      terminalSafeState: "No change to any configured value",
      recovery: "An approver decides",
      reconciliation: "Proposal aging reported",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-45",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90517, 90532, 90547],
    cells: {
      failureMode: "Lane-B auto-published patch fails distribution",
      detection: "Package distribution acknowledgement missing",
      operationalSeverity: "Major",
      frontlineMessage: "No message; the device keeps its pinned version",
      tenantWebMessage: "\"An approved change has not yet reached every device.\"",
      validationGate: "Distribution acknowledgement",
      retryLimit: "Register",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable — the run stays pinned, which is correct",
      firstFallback: "The device keeps its pinned version, which is always safe",
      fallbackOfFallback: "Manual redistribution",
      terminalSafeState: "Runs execute on their pinned version",
      recovery: "Distribution retried",
      reconciliation: "Per-device package inventory reconciled against the published version",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-46",
    family: "governance-evaluation-and-gate",
    attributeLocators: [90518, 90533, 90548],
    cells: {
      failureMode: "Model or package rollback while outputs are in flight",
      detection: "Rollback initiated with active runs",
      operationalSeverity: "Major",
      frontlineMessage: "\"Live coaching unavailable.\" briefly",
      tenantWebMessage: "\"A platform change is in progress. Some agent outputs are paused.\"",
      validationGate: "Evaluation gate re-asserted for the target version",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "The prior version is the alternate",
      partialOutput: "In-flight outputs complete or are quarantined; none are attributed to the wrong version",
      firstFallback: "Prior version continues serving",
      fallbackOfFallback: "Cached guidance then deterministic only",
      terminalSafeState: "Deterministic execution",
      recovery: "Target version passes evaluation and serves",
      reconciliation: "Outputs attributed to the version that produced them; no silent reattribution",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-47",
    family: "connectivity-device-and-sync",
    attributeLocators: [90623, 90636, 90649],
    cells: {
      failureMode: "Device offline at answer delivery",
      detection: "Delivery attempt with no device session",
      operationalSeverity: "Minor",
      frontlineMessage: "On return: \"Answer to your question from HH:MM\" with the staleness banner",
      tenantWebMessage: "\"One coaching answer is waiting for a device that is offline.\"",
      validationGate: "Revalidation before delivery",
      retryLimit: "Delivery retried at each sync until the horizon of `DEC-AISTALE-001`",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable — the answer is complete, merely undelivered",
      firstFallback: "Hold the answer server-side",
      fallbackOfFallback: "Surface it in the Client Command Center drill instead",
      terminalSafeState: "The answer is retained, never delivered to a phantom device",
      recovery: "Device returns",
      reconciliation: "Delivery state recorded honestly; nothing claims delivery",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: ["DEC-AISTALE-001"],
  },
  {
    id: "FAIL-AI-48",
    family: "connectivity-device-and-sync",
    attributeLocators: [90624, 90637, 90650],
    cells: {
      failureMode: "Device offline beyond the credential-trust window",
      detection: "Window expiry against last successful sync",
      operationalSeverity: "Major",
      frontlineMessage: "\"Connect to continue. Your saved work is safe.\"",
      tenantWebMessage: "\"A device has exceeded its offline trust window and requires a sync.\"",
      validationGate: "Credential-trust assertion",
      retryLimit: "Not applicable — the device must sync, not retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Forced sync before designated high-risk actions",
      fallbackOfFallback: "Restrict to steps that require no fresh authority",
      terminalSafeState: "Run parks; the worker continues other assigned runs",
      recovery: "Sync completes",
      reconciliation: "Credential freshness recorded per `E5` of the engineering design items",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-49",
    family: "connectivity-device-and-sync",
    attributeLocators: [90625, 90638, 90651],
    cells: {
      failureMode: "Command backlog with advisory content queued behind safety commands",
      detection: "Queue inspection at sync",
      operationalSeverity: "Minor",
      frontlineMessage: "No message; safety commands apply first",
      tenantWebMessage: "\"Pending platform actions are being applied in order.\"",
      validationGate: "Not applicable — ordering, not validation",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Apply safety commands first, advisory last",
      fallbackOfFallback: "Advisory content expires per `DEC-AISTALE-001` rather than blocking",
      terminalSafeState: "Safety commands always land",
      recovery: "Backlog drains",
      reconciliation: "Command states traversed distinctly, never collapsed into applied",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: ["DEC-AISTALE-001"],
  },
  {
    id: "FAIL-AI-50",
    family: "connectivity-device-and-sync",
    attributeLocators: [90626, 90639, 90652],
    cells: {
      failureMode: "Duplicate delivery of the same answer",
      detection: "Idempotency key collision",
      operationalSeverity: "Minor",
      frontlineMessage: "No message; the duplicate is discarded",
      tenantWebMessage: "\"No user-visible effect; recorded as a delivery anomaly.\"",
      validationGate: "Idempotency assertion",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "The duplicate is discarded, the event recorded",
      firstFallback: "Discard the duplicate",
      fallbackOfFallback: "Record the anomaly",
      terminalSafeState: "No user-visible effect",
      recovery: "Idempotency restored",
      reconciliation: "Duplicate rate monitored",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-51",
    family: "connectivity-device-and-sync",
    attributeLocators: [90627, 90640, 90653],
    cells: {
      failureMode: "Clock skew beyond threshold on the requesting device",
      detection: "Skew guard, default about five minutes, ceiling sixty",
      operationalSeverity: "Major",
      frontlineMessage: "\"This tablet's clock is wrong. Times you see may not match the record.\"",
      tenantWebMessage: "\"A device clock is out of tolerance; its conflicts route to review.\"",
      validationGate: "Skew guard",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Server-receipt ordering, which is already authoritative",
      fallbackOfFallback: "Route conflicts to the Client Command Center conflict-and-skew review",
      terminalSafeState: "Deterministic execution unaffected",
      recovery: "Clock corrected",
      reconciliation: "Conflicts resolved by human review, never by an untrusted clock",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-52",
    family: "connectivity-device-and-sync",
    attributeLocators: [90628, 90641, 90654],
    cells: {
      failureMode: "Device storage full, request cannot be queued",
      detection: "Write failure on the durable queue",
      operationalSeverity: "Major",
      frontlineMessage: "\"This tablet is out of space. Your captured work is safe. You cannot save new questions.\"",
      tenantWebMessage: "\"A device is reporting storage pressure.\"",
      validationGate: "Durable-write assertion before confirmation",
      retryLimit: "Not applicable — the queueing action is refused, never silently dropped",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Refuse the queueing action with a plain message",
      fallbackOfFallback: "Offer human escalation instead",
      terminalSafeState: "Captures and evidence retain priority over advisory data",
      recovery: "Storage freed after confirmed receipt plus integrity check",
      reconciliation: "`DEC-STORE-001` remains open; no behaviour is invented here",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: ["DEC-STORE-001"],
  },
  {
    id: "FAIL-AI-53",
    family: "connectivity-device-and-sync",
    attributeLocators: [90629, 90642, 90655],
    cells: {
      failureMode: "Work package invalid, unsigned, or version-mismatched",
      detection: "Signature and version verification at run open",
      operationalSeverity: "Critical",
      frontlineMessage: "\"This run cannot open on this tablet. Connect to get the correct approved version.\"",
      tenantWebMessage: "\"A device holds an invalid or mismatched work package.\"",
      validationGate: "Signature and version verification, hard",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable — nothing executes",
      firstFallback: "Refuse to open the run",
      fallbackOfFallback: "Worker reassigned to another run by the Supervisor",
      terminalSafeState: "No capture is taken against unverified content",
      recovery: "Package re-pulled",
      reconciliation: "The refused period recorded so the record gap has an explanation",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-54",
    family: "connectivity-device-and-sync",
    attributeLocators: [90630, 90643, 90656],
    cells: {
      failureMode: "Device wiped or de-authorised with queued requests pending",
      detection: "Wipe command with a non-empty queue",
      operationalSeverity: "Critical",
      frontlineMessage: "Compliance and de-authorisation case: the fixed suspension message where applicable",
      tenantWebMessage: "\"A device is being de-authorised; a final sync is being attempted.\"",
      validationGate: "Final-sync attempt before erasure",
      retryLimit: "Register for the final-sync attempt",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Queued requests upload with the final sync where possible",
      firstFallback: "Final sync attempt of pending captures and queued requests",
      fallbackOfFallback: "Where the device never returns, the answer and the request remain server-side against the run record",
      terminalSafeState: "Work is never silently destroyed",
      recovery: "Device returns or is written off",
      reconciliation: "`DEC-WIPE-001` remains open on how long a wipe may stay pending and what happens if the device never returns",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: ["DEC-WIPE-001"],
  },
  {
    id: "FAIL-AI-55",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90729, 90740, 90751],
    cells: {
      failureMode: "Partial output persisted before failure",
      detection: "Output present with no completion marker",
      operationalSeverity: "Major",
      frontlineMessage: "No message; nothing partial is ever shown",
      tenantWebMessage: "\"One agent output was incomplete and was not published.\"",
      validationGate: "Completion-marker assertion",
      retryLimit: "Not applicable — a partial output is never completed by retry",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Quarantined with its trace, retained, never published",
      firstFallback: "Suppress and fall back to cached guidance",
      fallbackOfFallback: "Deterministic only",
      terminalSafeState: "Nothing partial reaches any record",
      recovery: "Engineering fix",
      reconciliation: "Quarantined artifacts enumerated in the incident report",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-56",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90730, 90741, 90752],
    cells: {
      failureMode: "Answer arrives after the run finished",
      detection: "Delivery attempt against a finished run",
      operationalSeverity: "Minor",
      frontlineMessage: "\"This answer relates to a run that is now closed. It is advice only.\"",
      tenantWebMessage: "\"A coaching answer arrived after its run closed and was recorded, not applied.\"",
      validationGate: "Revalidation, which correctly still permits delivery as advisory",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Deliver as advisory against the closed record",
      fallbackOfFallback: "Record without delivery where the device never returns",
      terminalSafeState: "The finished record is not modified by the answer",
      recovery: "Not applicable — the record is correctly closed",
      reconciliation: "The answer appears in the record as an advisory artifact, not as a correction",
    },
    severity: { kind: 'band', band: "Minor", cell: "Minor" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-57",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90731, 90742, 90753],
    cells: {
      failureMode: "Answer arrives after worker substitution",
      detection: "Assignment changed between ask and answer",
      operationalSeverity: "Major",
      frontlineMessage: "Original worker: \"Your question was answered after you handed over.\" Substitute: no delivery",
      tenantWebMessage: "\"A coaching answer arrived after a substitution and was routed to the original worker's record.\"",
      validationGate: "Assignment assertion at delivery",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Route to the original worker's record",
      fallbackOfFallback: "Surface in the Client Command Center for the Supervisor",
      terminalSafeState: "Pre-substitution steps remain attributed to the original worker",
      recovery: "Not applicable",
      reconciliation: "Attribution preserved; the substitute is never shown another worker's answer",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-58",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90732, 90743, 90754],
    cells: {
      failureMode: "Answer arrives after a Severity 1 hold was placed",
      detection: "Hold present on the scope at delivery",
      operationalSeverity: "Major",
      frontlineMessage: "\"A hold is in force on this batch. This answer is advice about what happened, not an instruction for what to do now.\"",
      tenantWebMessage: "\"A coaching answer arrived against a held scope and is labelled advisory.\"",
      validationGate: "Hold assertion at delivery",
      retryLimit: "Not applicable",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Deliver with the hold-precedence banner",
      fallbackOfFallback: "Suppress if the hold scope makes the answer misleading",
      terminalSafeState: "The hold stands; only the Quality Manager releases it",
      recovery: "Hold released by the Quality Manager",
      reconciliation: "The answer is recorded against the deviation, not against the release decision",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-59",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90733, 90744, 90755],
    cells: {
      failureMode: "Reconciliation mismatch between trace, decision record, and operational record",
      detection: "Count comparison at reconciliation",
      operationalSeverity: "Critical",
      frontlineMessage: "No message",
      tenantWebMessage: "\"A record consistency check has been raised for review.\"",
      validationGate: "Count reconciliation",
      retryLimit: "Not applicable — a mismatch is investigated, not retried",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Any orphaned artifact is quarantined pending investigation",
      firstFallback: "Freeze reconciliation and raise for review",
      fallbackOfFallback: "Manual reconciliation by the platform team",
      terminalSafeState: "No record is altered until the mismatch is explained",
      recovery: "Root cause fixed",
      reconciliation: "Append-only annotations record what was corrected, by whom, and when",
    },
    severity: { kind: 'band', band: "Critical", cell: "Critical" },
    citedDecisions: [],
  },
  {
    id: "FAIL-AI-60",
    family: "recovery-reconciliation-and-stale-state",
    attributeLocators: [90734, 90745, 90756],
    cells: {
      failureMode: "Technical recovery complete but dashboards still stale",
      detection: "Component healthy while a dependent view has not recomputed",
      operationalSeverity: "Major",
      frontlineMessage: "No message",
      tenantWebMessage: "\"This view is still catching up. Last updated HH:MM.\"",
      validationGate: "Recompute-completion assertion per view",
      retryLimit: "Recompute retried per view",
      circuitBreaker: "Not applicable",
      alternateModel: "Not applicable",
      partialOutput: "Not applicable",
      firstFallback: "Show the stale marker with its true age",
      fallbackOfFallback: "Force a recompute",
      terminalSafeState: "The view is honest about being behind",
      recovery: "Recompute completes",
      reconciliation: "The incident cannot close while any dependent view is stale",
    },
    severity: { kind: 'band', band: "Major", cell: "Major" },
    citedDecisions: [],
  },
] as const satisfies readonly CatalogueRow[]

const BY_ID = new Map<string, CatalogueRow>(FAILURE_CATALOGUE.map((r) => [r.id, r]))

export function catalogueRow(id: string): CatalogueRow {
  const found = BY_ID.get(id)
  if (!found) throw new Error(`No catalogued failure is registered for ${id}.`)
  return found
}

const BINDING = new Map<SpineItemNumber, SpineBinding>(SPINE_BINDINGS.map((b) => [b.item, b]))

/**
 * The tables' own idiom for "this value is owed to the open register": the
 * bare token `Register`, or one of the register's identifiers. A cell naming a
 * decision that is NOT in the register — `DEC-AGENTLC-001` on `FAIL-AI-20`'s
 * reconciliation, for instance — is a deviation that happens to cite an open
 * decision elsewhere, and reading it as owed here would put an attribute in
 * the wrong register.
 */
function pointsAtTheRegister(cell: string): boolean {
  if (/(^|[\s(])Register\b/.test(cell)) return true
  return REGISTER_IDS.some((id) => cell.includes(id))
}

export type SpineResolution = 'inherited' | 'deviated' | 'owed'

/**
 * How one row resolves one spine attribute. Total over `SpineItemNumber`,
 * because `BINDING` is built from `SPINE_BINDINGS` and the test asserts that
 * list IS `SPINE_ITEM_NUMBERS`; a miss throws rather than defaulting to
 * `inherited`, which is the shape that would make `AC-43-101` unfalsifiable.
 */
export function spineResolution(row: CatalogueRow, item: SpineItemNumber): SpineResolution {
  const binding = BINDING.get(item)
  if (!binding) throw new Error(`No spine binding is registered for item ${String(item)}.`)
  if (binding.columns.length === 0) return 'inherited'
  if (binding.columns.some((c) => pointsAtTheRegister(row.cells[c]))) return 'owed'
  return binding.kind === 'selects' ? 'inherited' : 'deviated'
}

export function spineResolutions(row: CatalogueRow): Readonly<Record<SpineItemNumber, SpineResolution>> {
  return Object.fromEntries(
    SPINE_ITEM_NUMBERS.map((item) => [item, spineResolution(row, item)]),
  ) as Record<SpineItemNumber, SpineResolution>
}

/**
 * Re-derives the severity assignment from the row's own cell. Exported so the
 * stored assignment can be checked against the parser rather than trusted, and
 * so a later surface can ask the question without reaching into the record.
 */
export function severityOf(row: CatalogueRow): SeverityAssignment | null {
  return severityAssignment(row.cells.operationalSeverity)
}

/**
 * THIS MODULE'S SIDE OF THE `AC-43-301` SEAM (L90840), AND NOTHING MORE.
 *
 * `AC-43-301` requires that during any catalogued failure, all five surfaces
 * render a state drawn from the operating-mode vocabulary and that no two
 * surfaces contradict. That vocabulary is a SEPARATE object owned elsewhere in
 * this wave, and it is deliberately not imported, restated or validated
 * against here — a second copy of a closed vocabulary is a second thing to
 * keep true, and the copy is always the one that goes stale.
 *
 * What this module can honestly say is which mode identifiers its own cells
 * name. It returns them as opaque strings. Whoever owns the vocabulary is
 * responsible for the membership check, and this is the list they must cover.
 */
export function aiModesNamed(row: CatalogueRow): readonly string[] {
  return [...new Set([...JSON.stringify(row.cells).matchAll(/AIMODE-\d+/g)].map((m) => m[0]))].sort()
}

/** Every mode identifier the catalogue's own cells name, across all its rows. */
export function aiModesNamedByCatalogue(): readonly string[] {
  return [...new Set(FAILURE_CATALOGUE.flatMap(aiModesNamed))].sort()
}
